name: spotify_podcast_pipeline
version: "1.0.0"
config-version: 2

profile: spotify_podcast_pipeline

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_podcast_pipeline:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: analytics

seeds:
  spotify_podcast_pipeline:
    +schema: seeds
